<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
		<Configurations>Debug;Release;Debug (Dedicated);Release (Dedicated)</Configurations>
	</PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Usings\GlobalUsings.cs" Link="Usings/GlobalUsings.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Source.Common\Source.Common.csproj" />
    <ProjectReference Include="..\Source.GUI.Controls\Source.GUI.Controls.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="**\*" Exclude="**\*.cs;**\*.csproj;obj\**;bin\**;**\*_bak\**;sourceengine\**;platform\**;hl2\resource\**;hl2\gamemodes\**;hl2\lua\**;hl2\cache\workshop\**;hl2\maps\**;hl2\steam.inf;hl2\garrysmod_*.vpk;hl2\cfg\autoexec.cfg" CopyToOutputDirectory="PreserveNewest" />
    <None Remove="@(Content)" />
  </ItemGroup>

</Project>
